language: bash
dist: trusty

git:
  depth: 1

script:
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7 > /dev/null 2>&1
  - export CROSS_COMPILE=`pwd`/arm-eabi-4.7/bin/arm-eabi-
  - export ARCH=arm
  - export SUBARCH=arm
  - make ARCH=arm SUBARCH=arm gtel3g_defconfig
  - make ARCH=arm SUBARCH=arm -j4
